### ISSUE TITLE
建议添加跳转链接、显示作业内容，附件显示不全的bug

### ISSUE THREAD

**Issue by Steve-Strange** [FuryMartin/BUAA-SpocHelper#10]
希望能够增加一些直接跳转到spoc的链接，可以临时解决下述问题
希望添加作业内容的显示，目前无法分辨作业（
<img width="529" alt="image" src="https://user-images.githubusercontent.com/120027032/234744039-970dee7a-c090-4df2-9f07-4e9d05aba2b5.png">
附件显示不全，只得到五个
<img width="608" alt="image" src="https://user-images.githubusercontent.com/120027032/234744306-1f986296-308e-427e-a3c5-dbbbe17448db.png">
<img width="971" alt="image" src="https://user-images.githubusercontent.com/120027032/234744337-1c1d2999-c569-4292-b2ce-7e897a63a1ce.png">
<img width="975" alt="image" src="https://user-images.githubusercontent.com/120027032/234744363-622066b8-565f-47bf-a2da-4615b3fb09d0.png">
感谢大佬！

**Comment by FuryMartin** [comment]
## 关于问题1：

鼠标悬浮在"Attachment"上方可以查看作业详情

![image](https://user-images.githubusercontent.com/41051953/234746415-640a3a90-10e0-47db-8816-32471892246f.png)


## 关于问题2：

由于 Spoc 的设计问题，老师可以在多个地方（可以在 Spoc 上的"课前"、"课后"、"课程资料"处查看）上传课件资料，目前只实现了 "课前"、"课后"的资料查询，"课程资料"目前还没实现。

这主要是因为 Spoc 平台"课程资料"和"课前"、"课后"的功能设计有一些不同，前者提供整个课程组的资料，后两者提供本教学班的资料，考虑到都是课件，我希望能够将它们合并在一起呈现，但是目前还没想好完成这项工作，详见 https://github.com/FuryMartin/BUAA-SpocHelper/issues/8



PS：看起来 图1 中表示"已经提交过"的绿色按钮有点显示问题，不知道是不是因为分辨率问题导致的。我只在 2k 和 1080P 分辨率进行了测试，这两个分辨率应该是没问题。

**Comment by Steve-Strange** [comment]
ok感谢

**Comment by FuryMartin** [comment]
> 欸，但这些资料可以以文件夹的形式都放上来嘛

是这样，目前看只能新开一个 Page 然后专门放这部分东西了

**Comment by Steve-Strange** [comment]
ok感谢！
大佬辛苦！
