### ISSUE TITLE
有时“提交作业”按钮会变得很小，而且没有文字

### ISSUE THREAD

**Issue by SuzumiyaAkizuki** [FuryMartin/BUAA-SpocHelper#2]
![image](https://user-images.githubusercontent.com/81616766/232054001-5097a4c2-3f69-4832-b351-2c1b67953034.png)
如图所示

**Comment by FuryMartin** [comment]
这个问题我暂时无法复现，需要你提供更多信息。

能否请你登录 Spoc 网站，在《信息论基础》这门课的作业列表页记录一下资源请求情况？

具体操作是进入作业列表页，随后打开浏览器的开发者选项，进入”网络“或是"Network"选项卡，刷新网页，记录下 `queryZylmList_xs` 这个请求的响应，如图所示：

![image](https://user-images.githubusercontent.com/41051953/232079810-6c67a291-36f9-4a1c-8935-6c783861b09f.png)

随后将复制到的值以 `json` 格式粘贴

**Comment by FuryMartin** [comment]
已修复，问题原因：对于仅能提交一次的作业，按钮文本绑定出错

详情可见：https://github.com/FuryMartin/BUAA-SpocHelper/commit/7088a1b8efe335b34865711e415996893bace2db

**Comment by FuryMartin** [comment]
商店版已推送更新。
