### ISSUE TITLE
建议增加显示“作业内容”

### ISSUE THREAD

**Issue by SuzumiyaAkizuki** [FuryMartin/BUAA-SpocHelper#3]
![image](https://user-images.githubusercontent.com/81616766/232054282-375fd22c-aaed-447f-83e4-4d37528ad942.png)
即图中的部分

**Comment by FuryMartin** [comment]
已经在 8ded4c2 中进行修复，现在可以同时显示作业内容和附件名称了。

可以前往 [更新作业详情显示 #18](https://github.com/FuryMartin/BUAA-SpocHelper/actions/runs/4700768550) 下载 `SpocHelper_1.0.12.0_x64_Test-8ded4c2`， 解压后双击 `install.ps1` 完成临时证书验证即可安装。

商店版因为需要2-3天的审核，所以更新会延后。

![image](https://user-images.githubusercontent.com/41051953/232073535-36f92a12-2677-449a-859a-09ac42275cd6.png)
